### ISSUE TITLE
more examples!! ;-)

### ISSUE THREAD

**Issue by ozzyyzzo4096** [dciabrin/ngdevkit#1]
Hey! looks like a super cool project to get our hands on neo-geo using C language! :)

Adding few more examples about sprites, backgrounds, sound, synchro etc in 'C'  would be welcome!! 

What about some cygwin intructions for sdk installation for windows users? ;-)

Keep on the good work!

**Comment by dciabrin** [comment]
Just pushed two new examples:
- one for sprite creation, joystick handling , vertical blank interrupt.
- one for sprite animation, with uses a new tool for palette extraction.

They comes with some comments to help you get started. More will come eventually.

Meanwhile, I'll close this issue, don't hesitate to open a dedicated issue for tracking windows installation.

**Comment by ozzyyzzo4096** [comment]
It could be also very nice to expose timer interrupts with a callback system (if it make sense regarding rastertime cost of such a feature?)
