### ISSUE TITLE
Prerequisites: needed to setup deb-src repositories on Ubuntu

### ISSUE THREAD

**Issue by city41** [dciabrin/ngdevkit#10]
Thanks for making this dev kit!

When installing on Ubuntu 16.04, I'd get this error on the prerequisites: `Unable to find a source package for gcc-5` (and sdcc).

To get past this, I needed to go to `/etc/apt/sources.list` and uncomment all the `deb-src` repos. Not sure exactly which one I needed so I just uncommented all of them. Then `apt update`.

After doing that the dev kit installed without a hitch.

I figured I'd at least file an issue here in case other Ubuntu users hit this. I'm also happy to send a PR updating the README if you like.

**Comment by dciabrin** [comment]
Hey city41, sorry I overlooked your issue,

It seems that you opened #12 that provides a fix that would work for that issue as well?

I haven't got time to run bootstrap the devkit on either of those Ubuntu distro, but will do that shortly and report accordingly

**Comment by city41** [comment]
I mostly filed this and #12 in case other Ubuntu users have the same issue. Figure they’d find these and get unblocked. No real action is needed I don’t think.

**Comment by dciabrin** [comment]
Closing this one now as I believe the latest version of README-mingw.md has the explanation requested. Don't hesitate to re-open if I'm wrong.
