### ISSUE TITLE
Software DIP system doesn't work with optimized builds

### ISSUE THREAD

**Issue by gabordo** [dciabrin/ngdevkit#113]
Hi, I tried to add software DIP support to our game and I couldn't get it working. I tried to copy example 08's setup but no success. As an experiment I turned on different optimizations in the example's makefile and it broke example 08 too. It seems that adding -O1 is enough to break the example (I use -O3 and also link time optimization for our game).

**Comment by dciabrin** [comment]
I'll try to reproduce locally, can you be more specific about what it is that breaks with optimizations on?
 
Also, can you confirm that you're using a recent version of the linkscript provided with ngdevkit?
https://github.com/dciabrin/ngdevkit/blob/master/runtime/ngdevkit.ld

**Comment by gabordo** [comment]
I reinstalled msys2 and ngdevkit from scratch so I should be on the latest version. I compared my ngdevkit.ld to the link you gave me and they are identical.

You can reproduce the issue by adding -O1 to the makefile:
```
%.o: %.c
	$(M68KGCC) `pkg-config --cflags ngdevkit` -std=c99 -fomit-frame-pointer -O1 -g -c $< -o $@
```

And I managed to sidestep the issue by defining a dip_data_t structure and initializing it:
```
typedef struct dip_data_t {
	char title[16];
	u8 spec_data[6];
	u8 simple_data[10];
	char strs[8][12];
} dip_data_t;
#define dip_setup { \
	"TITLE           ", \
	{ 0xff,0xff,0xff,0xff,0x03,0x03 }, \
	{ 0x13,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00 }, \
	"LIVES       ", \
	"CONTINUES   ", \
	"DIFFICULTY  ", \
	"EASY        ", \
	"MEDIUM      ", \
	"HARD        ", \
}
#define DIPDATA __attribute__((section(".text.softdip,\"a\",@progbits \n* ")))
dip_data_t dip_jp_rom DIPDATA = dip_setup;
dip_data_t dip_us_rom DIPDATA = dip_setup;
dip_data_t dip_eu_rom DIPDATA = dip_setup;
```

**Comment by dciabrin** [comment]
Thanks, I can reliably reproduce locally now.
I'm trying to figure out how to fix that while still retaining the macro-based API.

**Comment by dciabrin** [comment]
OK I have reworked how the software DIPs are generated.
The DIP declaration stays the same, for instance with the example-08 from ngdevkit-examples:

```
#define DIP_TIME_OPTS(opt) opt(0,"ROUND TIME", 0x02, 0x30)
#define DIP_INT_OPTS(opt) opt(0,"FORCE", 20) opt(1,"RESPAWN", 3)
#define DIP_ENUM_OPTS(opt)                      \
    opt(0, "ANIMAL", ("CAT","DOG","PONY"), 2)   \
    opt(1, "VARIANT", ("SLOW","FAST"), 1)

#include <ngdevkit/soft-dip.h>
GENERATE_DIP(eu, "TEST DIP");
```

Using the preprocessor and disabling string padding, the devkit now generates a structure similar to what you posted:

```
$ m68k-neogeo-elf-gcc -O0 `pkg-config --cflags ngdevkit` -std=c99 -fomit-frame-pointer -D _DIP_NO_PADDING_ -E -P test.c

const rom_dip_t dip_eu_rom __attribute__((section(".text.softdip"))) = {
    .name = (dip_str16_t){.s = "TEST DIP"},
    .time_dips = {
        [0 ... 1] = {0xff, 0xff} ,
        [0] = {0x02, 0x30}
    },
    .int_dips = {
        [0 ... 1] = 0xff ,
        [0] = 20 , [1] = 3
    },
    .enum_dips = {
        [0 ... 9] = {0, 0} ,
        [0] = {2, 3} ,
        [1] = {1, 2}
    } ,
    .strings = {
        (dip_str12_t){.s = "ROUND TIME"} ,
        (dip_str12_t){.s = "FORCE"} ,
        (dip_str12_t){.s = "RESPAWN"} ,
        (dip_str12_t){.s = "ANIMAL"} ,
        (dip_str12_t){.s = "CAT"} ,
        (dip_str12_t){.s = "DOG"} ,
        (dip_str12_t){.s = "PONY"} ,
        (dip_str12_t){.s = "VARIANT"} ,
        (dip_str12_t){.s = "SLOW"} ,
        (dip_str12_t){.s = "FAST"}
    }
};

```
And objdump shows that the linking works with optimizations:

```
$ m68k-neogeo-elf-gcc -O3 `pkg-config --cflags ngdevkit` -std=c99 -fomit-frame-pointer -c test.c
$ m68k-neogeo-elf-objdump -d -j .text.softdip test.o

Disassembly of section .text.softdip:

00000000 <dip_eu_rom>:
   0:	54 45 53 54 20 44 49 50 20 20 20 20 20 20 20 20     TEST DIP        
  10:	02 30 ff ff 14 03 23 12 00 00 00 00 00 00 00 00     .0....#.........
  20:	52 4f 55 4e 44 20 54 49 4d 45 20 20 46 4f 52 43     ROUND TIME  FORC
  30:	45 20 20 20 20 20 20 20 52 45 53 50 41 57 4e 20     E       RESPAWN 
  40:	20 20 20 20 41 4e 49 4d 41 4c 20 20 20 20 20 20         ANIMAL      
  50:	43 41 54 20 20 20 20 20 20 20 20 20 44 4f 47 20     CAT         DOG 
  60:	20 20 20 20 20 20 20 20 50 4f 4e 59 20 20 20 20             PONY    
  70:	20 20 20 20 56 41 52 49 41 4e 54 20 20 20 20 20         VARIANT     
  80:	53 4c 4f 57 20 20 20 20 20 20 20 20 46 41 53 54     SLOW        FAST
  90:	20 20 20 20 20 20 20 20                                     
```

    
Now, accessing the DIP at runtime is unchanged, but I added a new introspection API since the devkit does no longer generate one symbol for each software DIP.

```
// Get the name of a DIP configured for this ROM
extern const dip_str12_t* bios_dip_name(u8 region, dip_type_t type, u8 num);

// Get the current value of an enum DIP as configured in backup RAM
extern const dip_str12_t* bios_dip_enum_choices(u8 region, u8 num);

```

In order to not break existing code, the devkit now provides macros that replace symbol_base accesses to call to this new API. I would suggest to drop the macro access in favour of this new API though.

I am fairly happy with the way it looks now and the seamless transition it provides, so unless you disagree I am going to merge that over the weekend. 

Thanks for reporting the original issue!

**Comment by gabordo** [comment]
It looks good to me, thank you for fixing it. We are about to wrap up this game and I'm neck deep in porting so I probably won't have time to test your changes for this game. But if we start another NeoGeo project I will definitely switch to your DIP setup.
