### ISSUE TITLE
Installing on Ubuntu 18.04, can't find <isl/band.h> [SOLVED]

### ISSUE THREAD

**Issue by city41** [dciabrin/ngdevkit#12]
Adding this here in case anyone else hits this.

On Ubuntu 18.04 I hit "no such file or directory" for `<isl/band.h>`

Easily solved with `apt install libisl-0.18-dev`

Don't forget to uncomment the `deb-src` repos in /etc/apt/sources.list as documented in the mingw/wsl README here in the repo.

**Comment by dciabrin** [comment]
Hey city41, thanks for taking the time to report that.

I'll test the update locally and update the README accordingly!
