### ISSUE TITLE
Problems with tiles rom on real hardware

### ISSUE THREAD

**Issue by totologic** [dciabrin/ngdevkit#14]
Hi.

I try to run some demos on the real Neo Geo hardware.

I use the NeoSD :
[The NeoSD](https://shop.terraonion.com/en/neo-geo-aes-home-console/11-neosd_aes-neo_geo_flashcart.html)

Whereas the fixed layer works well, the display for sprites has a problem. For example, the logo in the Sprite demo doesn't show:
[Video of Sprite Demo](https://youtu.be/RTDAmtVRwks)

Trying with with some demos I built (with map of 10000+ tiles), I started to see sprites on screen, but all is messy. I could guess from the results on screen that the tiles in the C-ROM don't start at the expected index.

You can compare:
[Video of my demo on MAME](https://youtu.be/MLb9eifG8Uc)

[Video of my demo on Neo Geo](https://youtu.be/9lPjmcMGtgg)

In your demo code you add this:
`/// First tile for the sprite in the ROM
#define START_TILE 60`

Is it related to our problem ? Why the 60 value ? On real hardware this value should be higher, but why ?

**Comment by totologic** [comment]
I have noticed the 3840 bytes size for tmp.c1 and tmp.c2 files, matching the 60 offset value for our start tile. Is there any reason for such a value or is it arbitrary ?

**Comment by dciabrin** [comment]
Hmm actually I just realized that the eye catcher was run from the emulator. Can you tell me whether it works on real hardware? maybe I got the analysis totally wrong in the first place :)

**Comment by totologic** [comment]
The eye catcher doesn't show on the hardware, it shows only on MAME.

I export the ROM for the NeoSD using a generic process (no checksum, no relation with an existing game). I used it to export the Neothunder homebrew (also based on PuzzleDePon rom) and it works fine.

I am going to investigate in my demo why some tiles show and some other don't. Maybe I will identify something.

Don't hesitate if you have any idea.

**Comment by totologic** [comment]
I did some experiments.

I did a swap of the c-rom files with the Neothunder homebrew. Results show the files exported by the titletool as safe (they display well in Neothunder). But the tiles from Neothunder don't show in the sprite demo, confirming something wrong with the code.

Then I wrote a simple rom tiles explorer. It is based on the sprite demo. It allows to show 64 successive tiles from the c-rom, starting from any point. The result is astonishing: the tiles show only from the 4036th place (maybe +/- 1). We can see it clealy at 00:49

[Demo tiles](https://youtu.be/L9yUIrRx5p4)

Does-it mean something to you ? We could hardcode the 4036 value but that would not be really satisfying :)

**Comment by totologic** [comment]
After playing a bit more, I found the exact offset in c-rom tile access is exactly 4096 (4036 as shown above which we add the 60 START_TILE value). I could play some demo adding this value in my code.

**Comment by city41** [comment]
I get the same results with this example on the NeoSD.

But I would argue the starting index of 60 for the tiles is correct, you can see that here:

![image](https://user-images.githubusercontent.com/141159/50943096-dfb22500-143f-11e9-8c23-01f24fe655d1.png)

Seems there is something wrong with the example's code.

FWIW, in general I have had a lot of success running stuff built with ngdevkit on NeoSD. This is the first time I have seen an issue like this.

**Comment by city41** [comment]
Also from what I can tell, the eyecatcher should not run at all for default ngdevkit games. Why MAME runs the eyecatcher I don't understand.

In ngdevkit's runtime, $122 jmp's to GAME_BOOT. $122 is where the game's USER subroutine handler needs to be

https://wiki.neogeodev.org/index.php?title=USER_subroutine

The first time it is called is for eyecatcher. But rather than respond to that, a ngdevkit game invokes main(). I hacked at crtS.0 to work around this: 

https://github.com/city41/ngdevkit/commit/2f3395ee5208c5bc5746f95434628bba75b53293

My hack causes ngdevkit to respond to eyecatcher and tell the bios to handle eyecatcher. Then the second time USER is called, main() is invoked.

**Comment by city41** [comment]
S ROMs have a max size of 128kb. ngdevkit generates S ROMs that are 1024kb. If an S ROM is larger than 128kb, bank switching is required:

https://wiki.neogeodev.org/index.php?title=S_ROM

**Comment by totologic** [comment]
I use the NeoBuilder.exe program provided by Terraonion.

**Comment by totologic** [comment]
Guys, that would be great to have a place to share our experiments and tricks on Neo Geo, Ngdevkit, NeoSD, maybe more.... I already have plenty of demos running on the real hardware. Any idea ?

**Comment by sreuter** [comment]
@totologic Same here, happy to host this for us on my Discord. https://discord.gg/FXwhA8P

**Comment by sreuter** [comment]
Btw, I spent some time night to get my homebrew game working on my cabinet using Darksoft's MultiMVS. Thanks to some of the instructions in this thread + some [MultiMVS specific instructions](https://www.arcade-projects.com/forums/index.php?thread/5055-darksoft-neo-multi-help-thread/) on how to compose the ROM!

Here's the quick and dirty gist:

```
mvsmulti:
	mkdir -p mvsmulti/
	./join_crom0.py # get this from https://www.arcade-projects.com/forums/index.php?thread/5055-darksoft-neo-multi-help-thread/
	cp rom/202-m1.m1 mvsmulti/m1rom
	cp rom/202-p1.p1 mvsmulti/prom
	dd if=rom/202-s1.s1 of=mvsmulti/srom bs=128k count=1
	cp rom/202-v1.v1 mvsmulti/vroma0
	echo -n "13" > mvsmulti/fpga
```

**Comment by dciabrin** [comment]
Hey @city41,

Thanks very much for troubleshooting that one.
Sorry for the awfully late answer, but I just fixed all the examples in ngdevkit-examples by following your advice.
So if you happen to re-run the devkit's examples on your real hardware and it doesn't work now, please shout and I'll revisit it (hopefully more diligently this time :P)
