### ISSUE TITLE
Problem with palette on real hardware

### ISSUE THREAD

**Issue by totologic** [dciabrin/ngdevkit#15]
Hi.

I met a serious issue on real hardware related to palette color mapping.

The 16 colors of a palette are not fully mapped on the tiles. Instead, it looks like only the 4 first colors are mapped.

A simple example, 4 sprites and 4 gradient palettes
[Result on Mame](https://i.imgur.com/z6auoH5.png)
[Result on hardware](https://i.imgur.com/lm0Br40.jpg)

I have this result using both the tiletool.py and my own png-to-crom conversion program.

Any idea ?

**Comment by dciabrin** [comment]
Fixing this long overdue issue, thanks!
