### ISSUE TITLE
Playing sound and music

### ISSUE THREAD

**Issue by totologic** [dciabrin/ngdevkit#16]
Hi.

Does the kit include a solution to play sounds and music ?

I made a demo using the NeoSound Z80 driver by Jeff Kurtz. iI works fine on MAME but it still stays mute on the real hardware.

Any idea why ? :)

**Comment by dciabrin** [comment]
Hey

> Does the kit include a solution to play sounds and music ?

Not yet unfortunately... although as a part of the solution, I provide sdcc as a z80 assembler and z80 C compiler, so my plan is to ultimately provide an open source mod player or something.

> I made a demo using the NeoSound Z80 driver by Jeff Kurtz. iI works fine on MAME but it still stays mute on the real hardware.
> 
> Any idea why ? :)

I'm afraid not :(

**Comment by totologic** [comment]
Fixed when truncated properly the S file as explained in #14
