### ISSUE TITLE
Neo Geo Splash screen jingle

### ISSUE THREAD

**Issue by totologic** [dciabrin/ngdevkit#22]
Hi !

First, I think you could be interested to see some results achieved with NGDEVKIT.

[Neotris DEMO 2](https://youtu.be/hCuBE5VdB0E)

Then, I could'nt figure out how to play the Neo Geo jingle while '330 MEGA PRO_GEAR SPEC'. Any idea ?

Last, it sounds fair to credit NGDEVKIT in my project. I could display a logo between the splash screen and the title screen. Fell free to provide any logo, image or animation of any kind.

**Comment by dciabrin** [comment]
Wow... Amazing work :+1:
Thanks for credits, I'm glad this devkit could be of any practical use for you :)

As for the "330 MEGA" message, I have no idea to be honest :D, maybe neogeodev wiki has some clue somewhere?

PS: as a quick heads up, ngdevkit is currently being refactored (tracked in #20), so I hope than before the end of the year we'll be able to

    apt-get install -y ngdevkit ngdevkit-gngeo

To make it easier for everyone to use it for their own project. Finger crossed!

**Comment by totologic** [comment]
Jingle can be added easily using the [great NGFX Builder from Blastar](https://blastar.citavia.de/index.php?id_post=41). Just need to check the option "Eyecatcher".

**Comment by dciabrin** [comment]
OK I might have totally misunderstood the original question....
Did you mean "how would I play the traditional BIOS music while the eye-catcher is running"? Or did you mean "Could I run the eye catcher with the later version of the message, i.e. Giga Shock something-something".

I originally thought you meant the latter, and in that case you can't do much apart from implementing a custom eye catcher and configure your ROM to use it at link time, as explained in #19.

But now I believe you asked for the former... and right now there's no sound option in the devkit unfortunately. nullsound is just barely enough to make your ROM boot on real hardware. Your best option is to use another sound driver, the neogeodev wiki has a good collection of those.

As for ngdevkit, my goal is to only rely on open source bits, so I'm considering implementing a sound driver that would play mods from bambootracker. But nothing's started yet.
