### ISSUE TITLE
ngdevkit install under windows 10 through Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by ozzyyzzo4096** [dciabrin/ngdevkit#3]
Hello,

It would be even better if ngdevkit will be available and/or accessible more directly for ppl like me using Windows10 for their everyday work! 

While installing ngdevkit using cygwin looks like a dead end.. i've been investigating WSL ->

I'm using this ->
https://www.linux.com/learn/intro-to-linux/2017/3/how-use-different-linux-bash-shells-windows-10 

Just because the 'easy' installation through the store (using debian linux app' doesn't work on my config..

So far, ngdevkit packages dependies were met and all packages were installed successfuly but some errors are remaining when calling ./make 

Please check the screenshots below : 

https://www.jeuxdecartes.ovh/data/wls.png
https://www.jeuxdecartes.ovh/data/dinfo.png

**Comment by dciabrin** [comment]
Hmm... this is probably the same problem I'm trying to workaround for homebrew on macOS.
Apparently ISL 0.19 doesn't ship a band.h anymore. Compilation works fine with ISL 0.18

Do you have any means of downgrading the version to verify?

**Comment by dciabrin** [comment]
OK I confirm that I can build gcc with WSL and ubuntu xenial, after fixing a few dependencies.

The problem now is that gngeo won't work out of the box because it's a graphical application and WSL doesn't mix well with Win10 for that.

I'm currently trying to build gngeo with mingw-64, so that the resulting binary doesn't depend on WSL and SDL and OpenGL can work properly. I'll do a dedicated README.win once I got that to work.

**Comment by dciabrin** [comment]
I've just pushed c655a25e0aaebdb9dce31c13f457a0a3fdc5ebfa for building the devkit with a native gngeo on windows with mingw. It includes a README-mingw.md that explains the steps to build the toolkit with WSL.

You need to delete ./toolchain/gngeo before rebuilding to pick up an up-to-date gngeo repo (currently dciabrin/gngeo@1bcd5a24eda2665d564ed53a58a1c0513a4f2488).

I still need to update the README with guidance on how to enable the OpenGL blitters in gngeo, but at least it's functional right now if you want to give it a try.

Also, the source level debugging extension is currently disabled, as I need to improve cross-compilation support of emudbg (probably by using autoconf).

**Comment by dciabrin** [comment]
Support for OpenGL blietter landed in https://github.com/dciabrin/ngdevkit/commit/3d6a1f087e02a260bb2597ca0b6ec24e58264358 and README-mingw.md updated.

Again, you need to delete ./toolchain/gngeo before rebuilding to pick up an up-to-date gngeo repo (at least https://github.com/dciabrin/gngeo/commit/a1ad31a3f7321be19263c4fba9acd3eceacd10c8).

emudbg remains to be ported for feature parity with Linux/macOS.

**Comment by dciabrin** [comment]
Closing now, as the last missing bit (emudb) was just ported to WSL.
