### ISSUE TITLE
Gngeo does not compile

### ISSUE THREAD

**Issue by tvoybro** [dciabrin/ngdevkit#34]
A couple of months ago I compiled your ngdevkit and everything worked great. Now I'm trying to compile the toolkit again, on the same OS (arcolinux), but I get a bunch of errors, here are a small part of them. 
![ksnip_20200521-165257](https://user-images.githubusercontent.com/40628707/82565737-93bed680-9b83-11ea-8126-0600c344936d.png)

**Comment by tvoybro** [comment]
I think I've got it, sorry

**Comment by dciabrin** [comment]
OK, I was worried I broke gngeo with recent commits...
If you feel something was unclear in the README and is worth enhancing, let me know and I'll see how to improve it.
