### ISSUE TITLE
Cygwin

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [dciabrin/ngdevkit#40]
Hello, Can You Make A Tutorial On How To Get NGDEVKIT Set Up On Cygwin

Thanks.

**Comment by dciabrin** [comment]
I'll try to get my hand on a cygwin env and see the gap for compiling the entire devkit (probably a dependency nightmare).

Meanwhile, have you try to compile it with WSL? It should be reasonably straightforward to use the devkit from a windows env, as WSL2 makes it easy to share files from and to the linux VM.

**Comment by dciabrin** [comment]
I made significant progress on #47, so I think it's worth dropping this one and focus on MSYS2 support.
Shout if you disagree.

**Comment by dciabrin** [comment]
Closing now as #47 is probably the way to go for native windows support
