### ISSUE TITLE
Registers in include/ngdevkit/registers.h should be casted to (volatile u8/16 *)

### ISSUE THREAD

**Issue by KScl** [dciabrin/ngdevkit#51]
... as opposed to (u8/16 *) like they currently are, to keep GCC from optimizing out register read/writes. Writing to VRAM with -O1 or higher is basically impossible otherwise.

**Comment by dciabrin** [comment]
Oops, you're right, the volatile keyword disappeared during the refactoring in 9adf0c6becfbf3100749d06c9cd7a3a515a4ef95.
I'm adding them back.
