### ISSUE TITLE
The toolchain won't compile correctly using g++ 11

### ISSUE THREAD

**Issue by GbaCretin** [dciabrin/ngdevkit#52]
The error is `error: use of an operand of type ‘bool’ in ‘operator++’ is forbidden in C++17`. This seems to happen because g++ 11 uses by default c++17 instead of c++14. This is confirmed by the fact that the toolchain does compile using g++ 10.

**Comment by dciabrin** [comment]
Thanks for the report, this will require a tweak to ngdevkit-toolchain.
Let me recompile my local version and see if a simple CXXFLAG tweak in ngdevkit-toolchain will fix the issue.
