### ISSUE TITLE
README-linux.md: ngdevkit.list sources list may be wrong and may miss readline-dev package dependency

### ISSUE THREAD

**Issue by khelkun** [dciabrin/ngdevkit#63]
[This line to create `/etc/apt/sources.list.d/ngdevkit.list` does not seem right in the README-linux.md](https://github.com/dciabrin/ngdevkit/blame/master/README-linux.md#L21)

I use Ubuntu focal 20.04.03 LTS (Focal Fossa) in a VM, and I had to use the following source lists:
```
echo "deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted" > /etc/apt/sources.list.d/ngdevkit.list
echo "deb-src http://archive.ubuntu.com/ubuntu/ focal universe" >> /etc/apt/sources.list.d/ngdevkit.lis
```

Also the make (or make install, I don't remember) did complain about `readline` which was not recent enough but I did have readline package installed and up to date. So I ran `apt install readline-dev` package and it fixed the make error.   

Note that I recently rebuild ngdevkit from a fresh clean repository clone on this VM and everything went fine.

My friend uses MX Linux 19.4 based on Debian 10 (Buster) and he had to use the following source lists:
```
echo "deb-src http://deb.debian.org/debian buster main" > /etc/apt/sources.list.d/ngdevkit.list
```
And also he had to `apt install readline-dev`.

**Comment by dciabrin** [comment]
Oops, this doc certainly got messed up during the last doc refactoring...
Thanks for the report, fixed.
