### ISSUE TITLE
06-sound-sample no sound on real hardware with NEOSD

### ISSUE THREAD

**Issue by khelkun** [dciabrin/ngdevkit#64]
We've been trying to run 06-sound-sample on Neogeo AES with a NEOSD cartdige.  
Someone has already achieved this successfully?

We use [neosdconv](https://github.com/city41/neosdconv) and it works fine with game roms downloaded from the web. But the 06-sound-sample rom does not have sound although the graphics are there and the buttons trigger on screen.

The issue is presumably about the sound driver MROM.

I thought the problem could  be the driver signature which I assume to be the [driver ID declared here](https://github.com/dciabrin/ngdevkit-examples/blob/master/06-sound-adpcma/user_commands.def#L41). So I tried to replace it with `%Ver 3.0 by MAKOTO.04/03/10 to SK%` which is the "Puzzle De Pon!" [sound driver signature according to the wiki](https://shop.terraonion.com/en/neo-geo-aes-home-console/11-neosd_aes-neo_geo_flashcart.html).

But it seems this lead is not the right one. Would you have any other ideas or tests to perform please?

**Comment by dciabrin** [comment]
This might very well be a timing issue in the code on real hardware. I started this default sound driver from scratch so it's very likely that the z80 code does not wait long enough on the ym2612 or something along those line.
There's no particular logic for sound driver check/enforcement in the hardware, so tweaking the driver ID won't change anything. I don't think that NEOSD would do any check on it either.

**Comment by khelkun** [comment]
So this may be related to [prepare_wait_in_ram_opcode macro](https://github.com/dciabrin/ngdevkit/blob/f845e9c40fb9c8f6ee562933fb08a311785667ae/nullsound/macros/nullsound.def#L60) and its usage in the [MROM init](https://github.com/dciabrin/ngdevkit/blob/f845e9c40fb9c8f6ee562933fb08a311785667ae/nullsound/driver/nullsound.s#L45) and the [snd_command_01_prepare_for_rom_switch](https://github.com/dciabrin/ngdevkit/blob/f845e9c40fb9c8f6ee562933fb08a311785667ae/nullsound/driver/nullsound_commands.s#L48)?

**Comment by dciabrin** [comment]
> So this may be related to [prepare_wait_in_ram_opcode macro](https://github.com/dciabrin/ngdevkit/blob/f845e9c40fb9c8f6ee562933fb08a311785667ae/nullsound/macros/nullsound.def#L60) and its usage in the [MROM init](https://github.com/dciabrin/ngdevkit/blob/f845e9c40fb9c8f6ee562933fb08a311785667ae/nullsound/driver/nullsound.s#L45) and the [snd_command_01_prepare_for_rom_switch](https://github.com/dciabrin/ngdevkit/blob/f845e9c40fb9c8f6ee562933fb08a311785667ae/nullsound/driver/nullsound_commands.s#L48)?

So I think that this one shouldn't but the culprit, because unless it's buggy it's just meant to make the z80 read its code from RAM, to leave time to the m68k to initialize everything and switch to whatever z80 code bank is needed.

I'm more thinking something is wrong in https://github.com/dciabrin/ngdevkit/blob/f845e9c40fb9c8f6ee562933fb08a311785667ae/nullsound/driver/ym2610.s, because successive calls to the ym2610 have to respect some latency [1,2] to be effectively honored by the ym2610. And usually the emulators aren't that sensible to that, so we're overlooking some bugs on the real hardware.  

[1] http://www.ajworld.net/neogeodev/ym2610am2.html#Status
[2] http://www.ajworld.net/neogeodev/ym2610am2.html#RegWriting

**Comment by dciabrin** [comment]
Also https://wiki.neogeodev.org/index.php?title=Z80/YM2610_interface is probably a more specific answer to my previous comment.

**Comment by khelkun** [comment]
Cool that seems to be the right lead. I'l try to fix this and send you a PR if I succeed. thanks

**Comment by dciabrin** [comment]
After an awfully long hiatus, I just noticed that example 06 doesn't seem to run on MAME either. So while it's nothing close to being fixed, at least it doesn't require me from getting my hands on a neosd to test that on real hardware.

**Comment by dciabrin** [comment]
OK I think https://github.com/dciabrin/ngdevkit/commit/859fc942c3e073780165094c72f192c0bcb9d05d should fix this issue. It looks like the z80 was never initialized properly so it couldn't receive NMI when the 68k was triggering a sound command.
I don't have a way to test this fix on real hardware, but Mame is usually pretty spot on for NeoGeo, so I believe this patch should fix the original issue.
Closing accordingly.
