### ISSUE TITLE
Makefile Issue In Terminal

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [dciabrin/ngdevkit#65]
Hey, so anyways i keep getting this message int the terminal when i type make in the terminal there is a error and the error says m68k-neogeo-elf-gcc `pkg-config --cflags ngdevkit` -std=c99 -fomit-frame-pointer -g -c main.c -o main.o
m68k-neogeo-elf-gcc -o rom.elf main.o `pkg-config --libs ngdevkit`
mkdir rom
m68k-neogeo-elf-objcopy -O binary -S -R .comment rom.elf rom/202-p1.p1 && dd if=rom/202-p1.p1 of=rom/202-p1.p1 conv=notrunc,swab
1024+0 records in
1024+0 records out
524288 bytes (524 kB, 512 KiB) copied, 0.0116135 s, 45.1 MB/s
make -C ../assets
make[1]: *** ../assets: No such file or directory.  Stop.
make: *** [Makefile:30: ../assets/rom/c1.bin] Error 2
so can you help me please!

**Comment by dciabrin** [comment]
youy're trying to compile your example out of tree, you didn't copy the directory "./assets" from ngdevkit-examples.
Make sure you copy it one directory below where you're trying to compile your code

**Comment by NeoGeoFreak2004** [comment]
I think I copied the assets folder from the standalone examples folders, so how do I make my project without any errors?

**Comment by NeoGeoFreak2004** [comment]
Now its saying make: *** No rule to make target 'main.o', needed by 'rom.elf'.  Stop. so how do i compile it corectly in the terminal?
