### ISSUE TITLE
Use the open source bios with roms not made with NGDevKit.

### ISSUE THREAD

**Issue by kakoeimon** [dciabrin/ngdevkit#66]
Hi.
This is not an issue of ngdevkit.
I am trying to use the open source bios with a project of mine not made with NGDevKit, but the emulator runs and I get a black screen.

Can you point me to the right direction of making this to work or make the open source bios more "universal"?

**Comment by dciabrin** [comment]
So unfortunately this very likely expected. nullbios only provides right now the necessary mechanics to boot up the hardware up to the program ROM, and also provides means to poll inputs and populate various variables in memory like the real ROM would.

It doesn't implements all the API calls that the real ROM provides, It's a small dozen, but the devkit provides c-based function to print on screen, clear sprites, clear tiles... So i never took the time to mock those out to be a feature-compatible BIOS.

From [neogeodev's](wiki.neogeodev.org) wiki, it appears that [NeopenBIOS](https://github.com/neogeodev/neopenbios)  is another open source BIOS which looks more complete than mine (although the goal is not the same really: mine is just there to allow your ngdevkit ROMs to run on an emulator).

If you really want to make it work as a full replacement ROM, you'd have to implement all the BIOS syscalls as described in neogeodev wiki.

**Comment by kakoeimon** [comment]
Thanks. I close this as it is not an issue.
