### ISSUE TITLE
Understanding the dark bit in color definition

### ISSUE THREAD

**Issue by totologic** [dciabrin/ngdevkit#7]
Hi.

I'm trying to play with the 16bits colors system. My reference is the Neo Geo dev wiki page:

https://wiki.neogeodev.org/index.php?title=Colors

Encoding colors is not a problem, but I couldn't see the role played by the **dark bit**. It should be the least significant bit shared by the 3 channels but in practice I can't see any difference when set to 0 or 1.

For example, given two red value 0xcf00 and 0x4f00. In binary (dark bit in bold) :
0xcf00 -> **1**100 1111 0000 0000
0x4f00 -> **0**100 1111 0000 0000

Then distributing the dark bit to each channels (in bold) and reordering them, it gives the following channels composition: 
0xcf00 -> R(11111**1**) G(00000**1**) B(00000**1**)
0x4f00 -> R(11111**0**) G(00000**0**) B(00000**0**)

In consequence, 0xcf00 should appear a bit more saturated and lighter than 0x4f00. But on my screen both appear as full saturated red value 24bits (0xFF0000).

Did I miss something ? Maybe my understanding is incorrect ? Or an issue in color space projection ? (at this point I still use my old MAME for testing).

**Comment by dciabrin** [comment]
Your understanding is correct (I understand the same thing at least :P). This is more of an emulator issue actually..

I don't know how MAME works, but for the gngeo fork that is used in ngdevkit, there are at least two problems which prevents the emulator from honoring this dark bit:
  * The internal SDL surface which is used by gngeo to render the screen pixels (both sprites and fix tiles on top) is created as a 16bits RGB surface [1], with 5bits for Red, 6bits for Green, and 5bits for Blue. So dark bit isn't rendered for at least Red and Blue components.
  * Palette emulation [2] actually disregards this dark bit altogether. Internally, when a word is written in palette address space, gngeo only keeps the 5 most significant bits for all Red, Green and Blue components. As such, it also discards the Least significant Green bit, which in theory could have been preserved.

I'm afraid your version MAME is affected by the same limitation unfortunately...

[1] https://github.com/dciabrin/gngeo/blob/glsl/src/screen.c#L444
[2] https://github.com/dciabrin/gngeo/blob/glsl/src/memory.c#L527

**Comment by totologic** [comment]
OK I see. Thank you for sharing these accurate informations.

**Comment by city41** [comment]
I think the dark bit works the opposite way. When it is set, it sets the LSB of each color channel to zero. When it is unset, it sets the LSB to 1. I believe that is why it they call it "dark" as setting it darkens the color.

On the color converter on neogeodev, when you enter R:250, G:0, B:0, you get `$CF00`, and R:255, G:5, B:5 yields `$4F00`. Which supports the idea that the dark bit clears the LSB.

I am still trying to understand the dark bit myself. This thread on yaronet seems to strongly suggest the dark bit has a very subtle effect, almost imperceptible: https://www.yaronet.com/topics/185137-neogeo-graphicseditor-any-wishesrequestsrecommendations

For example, this color chart for green from that thread. When the dark bit is the only difference, the colors look pretty much identical 

![image](https://user-images.githubusercontent.com/141159/50946356-a54f8480-144d-11e9-93a7-e496f8b0a79a.png)

**Comment by totologic** [comment]
I have ordered an OSSC to display sharp pixels and accurate colors on TV and VGA screen. I will do a summary.

**Comment by dciabrin** [comment]
Thank you all for your inputs.

I've patched GnGeo to support full 24bits RGB color, so all the colors from the Neo Geo palette should now be visible on the emulator. To demonstrate that, I also added an example that uses the dark bit in color palettes to render 60 colors gradients.
paltool.py should also take care of the dark bit now.

I'm closing the issue accordingly.
