### ISSUE TITLE
unable to locate package error

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [dciabrin/ngdevkit#77]
hey yall, so anyways i was trying to install ngdevkit on ubuntu 22.04 but when i try to install this pops up: Unable to locate package ngdevkit Unable to locate package ngdevkit-gngeo
idk what this means so can you try to help me please!

**Comment by dciabrin** [comment]
Oops, Jammy Jellifish has been GA but I haven't tweak the recipes in launchpad to build daily packages for it, it's stuck on Impish Indri.
Let me fix that and request a rebuild in launchpad.

**Comment by dciabrin** [comment]
Heads up, ngdevkit-toolchain does not build on Jammy [1], I have to check if this is a compilation issue with recent g++ or if it's a debian build flags issue. Investigation is on the way...

[1] https://launchpadlibrarian.net/594335600/buildlog_ubuntu-jammy-amd64.ngdevkit-toolchain_0.1+202204011652-12~ubuntu22.04.1_BUILDING.txt.gz

**Comment by NeoGeoFreak2004** [comment]
Maybe I should try to use Ubuntu 20.04 for now.

**Comment by dciabrin** [comment]
If you didn't downgrade it's no longer necessary. I fixed the debian compilation issue [1], and the packages have just made it to the ngdevkit PPA:

```
# apt-cache policy ngdevkit
ngdevkit:
  Installed: 0.2+202112251421-13~ubuntu22.04.1
  Candidate: 0.2+202112251421-13~ubuntu22.04.1
  Version table:
 *** 0.2+202112251421-13~ubuntu22.04.1 500
        500 https://ppa.launchpadcontent.net/dciabrin/ngdevkit/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

I'm closing the issue accordingly. Thanks!

[1] https://github.com/dciabrin/ngdevkit-toolchain/commit/eaf336e0fab1ebdd5301997477ba87dcef78cdb1
