### ISSUE TITLE
Typo in README-mingw.md

### ISSUE THREAD

**Issue by mbaldessari** [dciabrin/ngdevkit#79]
`X server to run it. You also gget all the advantage of native`

s/gget/get/

**Comment by jeckersb** [comment]
```don't need a X server to run it```

s/ a / an /

**Comment by lmiccini** [comment]
💯

**Comment by beekhof** [comment]
Also s/not/now/ in `Windows 10 support is not achieved via MSYS2.` ?

**Comment by dciabrin** [comment]
By popular demand
