### ISSUE TITLE
_backup_ram variables are getting overwritten and clobbered

### ISSUE THREAD

**Issue by KScl** [dciabrin/ngdevkit#82]
The loop to clear out the .bss segment is also clearing out _backup_ram variables, essentially leading to all data being lost whenever the game starts up again. In addition, _backup_ram variables are (apparently?) being completely disregarded later on down the line, leading to other variables residing in the same areas of memory (and thus, data getting clobbered upon attempting to use either of them.)

The former is immediately apparent in example 11 (the scores and "highest level" never increase like they should be doing).

The latter isn't as obvious in the same example, as it only uses 5 bytes worth of data; however, extending the "scores" array to [32] entries instead of [2] also makes it apparent: The location of "foo", displayed on the screen, does not change at all; and altering the code to write to and read from [30] and [31] (as opposed to [0] and [1]), which seemingly should have no effect on the program's execution, will show that the text buffer is clobbering the scores array.

**Comment by dciabrin** [comment]
Argh, apologies for the inconvenience... I'll have another go at the linkscript soon.
Thanks for the detailed bug report.

**Comment by dciabrin** [comment]
I think the linkscript is now fixed, the start of the bss segment is now correctly correctly generated at link-time (starts right after the backup RAM):

```
nm rom.elf | grep -e rom_mem -e bss_start_in_ram
00100008 T __bss_start_in_ram
00100000 T rom_mem_backup
00000008 T rom_mem_backup_size
```

I can see the variables being updated in example 11, and re-running the example picks up the last values as expected.

The nightly packages will get automatically rebuilt shortly.
