### ISSUE TITLE
Black screen in Gngeo on macOS

### ISSUE THREAD

**Issue by superjohan** [dciabrin/ngdevkit#9]
After October's WSL fixes, building the devkit on macOS results in a Gngeo that doesn't draw anything. Keyboard input still works (e.g. pressing esc + up + enter quits the app)

I'm backtracking through the commits now to see what breaks it, but I could reproduce this on my other Mac which already had a working ngdevkit from before.

**Comment by dciabrin** [comment]
Hi thanks for the report, it might have broken something in https://github.com/dciabrin/gngeo (unlikely) or in https://github.com/dciabrin/ngdevkit/issues/9 (more likely). I'm going to compile locally and will try to figure it out.

Do you mind telling me which version of macOS you're running on?

**Comment by superjohan** [comment]
10.14.1 on both computers, although the build that works was built on 10.14.0, in case something has changed between macOS versions.

**Comment by dciabrin** [comment]
OK I was running 10.14.0, upgrading to 10.14.1 before I recompile.

**Comment by dciabrin** [comment]
Hmmm OK with my previous build (which I believe was working fine) I'm having the same black screen symptom when running on 10.14.1.
Investigation in progress, will report hopefully shortly

**Comment by dciabrin** [comment]
Probably related to https://bugzilla.libsdl.org/show_bug.cgi?id=4272

**Comment by dciabrin** [comment]
Yes, when you run gngeo with the glsl blitter, you have the ability to resize window. Doing so fixes the black screen and rendering starts to appear, as reported in the bugzilla mentionned above.

Unfortunately, latest stable sdl2 in brew does not fix that yet (2.0.8 as I'm writing that comment)

**Comment by dciabrin** [comment]
Closing the issue now as the issue doesn't reproduce on the latest macOS 10.15. Tested with the pre-built binaries available in brew (see #31).
